// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/session.proto

// Package common.v1 содержит общие модели для IAM сервиса

package common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Session представляет сессию пользователя
type Session struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_uuid уникальный идентификатор сессии
	SessionUuid string `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
	// user_uuid UUID пользователя, которому принадлежит сессия
	UserUuid string `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// created_at время создания сессии
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// expires_at время истечения сессии
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_common_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_common_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

func (x *Session) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *Session) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_common_v1_session_proto protoreflect.FileDescriptor

const file_common_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x17common/v1/session.proto\x12\tcommon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\aSession\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtBDZBgithub.com/linemk/rocket-shop/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_session_proto_rawDescOnce sync.Once
	file_common_v1_session_proto_rawDescData []byte
)

func file_common_v1_session_proto_rawDescGZIP() []byte {
	file_common_v1_session_proto_rawDescOnce.Do(func() {
		file_common_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_session_proto_rawDesc), len(file_common_v1_session_proto_rawDesc)))
	})
	return file_common_v1_session_proto_rawDescData
}

var file_common_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_session_proto_goTypes = []any{
	(*Session)(nil),               // 0: common.v1.Session
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_common_v1_session_proto_depIdxs = []int32{
	1, // 0: common.v1.Session.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: common.v1.Session.expires_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_v1_session_proto_init() }
func file_common_v1_session_proto_init() {
	if File_common_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_session_proto_rawDesc), len(file_common_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_session_proto_goTypes,
		DependencyIndexes: file_common_v1_session_proto_depIdxs,
		MessageInfos:      file_common_v1_session_proto_msgTypes,
	}.Build()
	File_common_v1_session_proto = out.File
	file_common_v1_session_proto_goTypes = nil
	file_common_v1_session_proto_depIdxs = nil
}
