// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/user.proto

// Package common.v1 содержит общие модели для IAM сервиса

package common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User представляет пользователя в системе
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_uuid уникальный идентификатор пользователя
	UserUuid string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// login логин пользователя
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	// email email пользователя
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// notification_methods каналы для получения уведомлений
	NotificationMethods []*NotificationMethod `protobuf:"bytes,4,rep,name=notification_methods,json=notificationMethods,proto3" json:"notification_methods,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_common_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetNotificationMethods() []*NotificationMethod {
	if x != nil {
		return x.NotificationMethods
	}
	return nil
}

// NotificationMethod представляет канал для уведомлений
type NotificationMethod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider_name имя провайдера (telegram, email, push)
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// target адрес получателя (email, ID чата и т.д.)
	Target        string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMethod) Reset() {
	*x = NotificationMethod{}
	mi := &file_common_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMethod) ProtoMessage() {}

func (x *NotificationMethod) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMethod.ProtoReflect.Descriptor instead.
func (*NotificationMethod) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationMethod) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *NotificationMethod) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_common_v1_user_proto protoreflect.FileDescriptor

const file_common_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x14common/v1/user.proto\x12\tcommon.v1\"\xa1\x01\n" +
	"\x04User\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12P\n" +
	"\x14notification_methods\x18\x04 \x03(\v2\x1d.common.v1.NotificationMethodR\x13notificationMethods\"Q\n" +
	"\x12NotificationMethod\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06targetBDZBgithub.com/linemk/rocket-shop/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_user_proto_rawDescOnce sync.Once
	file_common_v1_user_proto_rawDescData []byte
)

func file_common_v1_user_proto_rawDescGZIP() []byte {
	file_common_v1_user_proto_rawDescOnce.Do(func() {
		file_common_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_user_proto_rawDesc), len(file_common_v1_user_proto_rawDesc)))
	})
	return file_common_v1_user_proto_rawDescData
}

var file_common_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_v1_user_proto_goTypes = []any{
	(*User)(nil),               // 0: common.v1.User
	(*NotificationMethod)(nil), // 1: common.v1.NotificationMethod
}
var file_common_v1_user_proto_depIdxs = []int32{
	1, // 0: common.v1.User.notification_methods:type_name -> common.v1.NotificationMethod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_user_proto_init() }
func file_common_v1_user_proto_init() {
	if File_common_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_user_proto_rawDesc), len(file_common_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_user_proto_goTypes,
		DependencyIndexes: file_common_v1_user_proto_depIdxs,
		MessageInfos:      file_common_v1_user_proto_msgTypes,
	}.Build()
	File_common_v1_user_proto = out.File
	file_common_v1_user_proto_goTypes = nil
	file_common_v1_user_proto_depIdxs = nil
}
