// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/linemk/rocket-shop/order/internal/service (interfaces: OrderProducerService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	events "github.com/linemk/rocket-shop/order/internal/entyties/events"
)

// MockOrderProducerService is a mock of OrderProducerService interface.
type MockOrderProducerService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderProducerServiceMockRecorder
}

// MockOrderProducerServiceMockRecorder is the mock recorder for MockOrderProducerService.
type MockOrderProducerServiceMockRecorder struct {
	mock *MockOrderProducerService
}

// NewMockOrderProducerService creates a new mock instance.
func NewMockOrderProducerService(ctrl *gomock.Controller) *MockOrderProducerService {
	mock := &MockOrderProducerService{ctrl: ctrl}
	mock.recorder = &MockOrderProducerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderProducerService) EXPECT() *MockOrderProducerServiceMockRecorder {
	return m.recorder
}

// SendOrderPaid mocks base method.
func (m *MockOrderProducerService) SendOrderPaid(arg0 context.Context, arg1 *events.OrderPaidEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOrderPaid", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendOrderPaid indicates an expected call of SendOrderPaid.
func (mr *MockOrderProducerServiceMockRecorder) SendOrderPaid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOrderPaid", reflect.TypeOf((*MockOrderProducerService)(nil).SendOrderPaid), arg0, arg1)
}
