// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/linemk/rocket-shop/inventory/internal/usecase (interfaces: InventoryUseCase)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/linemk/rocket-shop/inventory/internal/entyties/models"
)

// MockInventoryUseCase is a mock of InventoryUseCase interface.
type MockInventoryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryUseCaseMockRecorder
}

// MockInventoryUseCaseMockRecorder is the mock recorder for MockInventoryUseCase.
type MockInventoryUseCaseMockRecorder struct {
	mock *MockInventoryUseCase
}

// NewMockInventoryUseCase creates a new mock instance.
func NewMockInventoryUseCase(ctrl *gomock.Controller) *MockInventoryUseCase {
	mock := &MockInventoryUseCase{ctrl: ctrl}
	mock.recorder = &MockInventoryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryUseCase) EXPECT() *MockInventoryUseCaseMockRecorder {
	return m.recorder
}

// CreatePart mocks base method.
func (m *MockInventoryUseCase) CreatePart(arg0 context.Context, arg1 models.Part) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePart", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePart indicates an expected call of CreatePart.
func (mr *MockInventoryUseCaseMockRecorder) CreatePart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePart", reflect.TypeOf((*MockInventoryUseCase)(nil).CreatePart), arg0, arg1)
}

// DeletePart mocks base method.
func (m *MockInventoryUseCase) DeletePart(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePart", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePart indicates an expected call of DeletePart.
func (mr *MockInventoryUseCaseMockRecorder) DeletePart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePart", reflect.TypeOf((*MockInventoryUseCase)(nil).DeletePart), arg0, arg1)
}

// GetPart mocks base method.
func (m *MockInventoryUseCase) GetPart(arg0 context.Context, arg1 string) (models.PartInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPart", arg0, arg1)
	ret0, _ := ret[0].(models.PartInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPart indicates an expected call of GetPart.
func (mr *MockInventoryUseCaseMockRecorder) GetPart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPart", reflect.TypeOf((*MockInventoryUseCase)(nil).GetPart), arg0, arg1)
}

// ListParts mocks base method.
func (m *MockInventoryUseCase) ListParts(arg0 context.Context, arg1 models.PartFilter) ([]models.PartInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListParts", arg0, arg1)
	ret0, _ := ret[0].([]models.PartInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListParts indicates an expected call of ListParts.
func (mr *MockInventoryUseCaseMockRecorder) ListParts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListParts", reflect.TypeOf((*MockInventoryUseCase)(nil).ListParts), arg0, arg1)
}

// UpdatePart mocks base method.
func (m *MockInventoryUseCase) UpdatePart(arg0 context.Context, arg1 string, arg2 models.Part) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePart", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePart indicates an expected call of UpdatePart.
func (mr *MockInventoryUseCaseMockRecorder) UpdatePart(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePart", reflect.TypeOf((*MockInventoryUseCase)(nil).UpdatePart), arg0, arg1, arg2)
}
