openapi: 3.0.3

info:
  title: OrderService API
  version: 1.0.0
  description: API для работы с сервисом заказов космических кораблей
x-ogen:
  target: ./shared/pkg/openapi/order/v1
  package: order_v1
  clean: true

tags:
  - name: OrderService
    description: Операции с данными о заказе космических кораблей - создание, оплата и другое

paths:
  /api/v1/orders:
    $ref: ./paths/orders_create.yaml
  /api/v1/orders/{order_uuid}:
    $ref: ./paths/orders_get.yaml
  /api/v1/orders/{order_uuid}/pay:
    $ref: ./paths/order_pay.yaml
  /api/v1/orders/{order_uuid}/cancel:
    $ref: ./paths/order_cancel.yaml
  
