// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements CancelOrder operation.
//
// Отменяет заказ. Проверяет статус заказа - если
// PENDING_PAYMENT, меняет статус на CANCELLED. Если PAID, возвращает
// ошибку 409.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements CreateOrder operation.
//
// Создает новый заказ на основе выбранных
// пользователем деталей. Проверяет наличие деталей в
// инвентаре и рассчитывает общую стоимость.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrder(ctx context.Context, req OptCreateOrderReq) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrder implements GetOrder operation.
//
// Get order by uuid.
//
// GET /api/v1/orders
func (UnimplementedHandler) GetOrder(ctx context.Context, params GetOrderParams) (r GetOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayOrder implements PayOrder operation.
//
// Проводит оплату ранее созданного заказа. Находит
// заказ по UUID, вызывает PaymentService для обработки платежа и
// обновляет статус заказа.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayOrder(ctx context.Context, req *PayOrderReq, params PayOrderParams) (r PayOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *UnexpectedErrStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *UnexpectedErrStatusCode) {
	r = new(UnexpectedErrStatusCode)
	return r
}
