// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements CancelOrder operation.
	//
	// Отменяет заказ. Проверяет статус заказа - если
	// PENDING_PAYMENT, меняет статус на CANCELLED. Если PAID, возвращает
	// ошибку 409.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrder implements CreateOrder operation.
	//
	// Создает новый заказ на основе выбранных
	// пользователем деталей. Проверяет наличие деталей в
	// инвентаре и рассчитывает общую стоимость.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req OptCreateOrderReq) (CreateOrderRes, error)
	// GetOrder implements GetOrder operation.
	//
	// Get order by uuid.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrder(ctx context.Context, params GetOrderParams) (GetOrderRes, error)
	// PayOrder implements PayOrder operation.
	//
	// Проводит оплату ранее созданного заказа. Находит
	// заказ по UUID, вызывает PaymentService для обработки платежа и
	// обновляет статус заказа.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderReq, params PayOrderParams) (PayOrderRes, error)
	// NewError creates *UnexpectedErrStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *UnexpectedErrStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
