name: Lint Reusable

on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string
      go-version:
        required: true
        type: string
      golangci-lint-version:
        required: true
        type: string

jobs:
  golangci-lint:
    name: Lint all Go modules
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4.2.2

      - name: 🛠 Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: ${{ inputs.go-version }}

      - name: 🏗 Create Go workspace
        run: |
            echo "🏗 Создаем Go workspace..."
            go work init
            for mod in ${{ inputs.modules }}; do
              if [ -d "$mod" ]; then
                echo "🏗 Добавляем модуль $mod в workspace"
                go work use "$mod"
              fi
            done
            echo "📋 Содержимое go.work:"
            cat go.work
      

      - name: 📌 Install Task
        uses: arduino/setup-task@v2.0.0

      - name: 🔧 Install dependencies for all modules
        run: |
            echo "🔧 Устанавливаем зависимости для всех модулей в workspace..."
            go work sync
            for mod in ${{ inputs.modules }}; do
              if [ -d "$mod" ]; then
                echo "🔧 Устанавливаем зависимости для $mod"
                cd "$mod" && go mod download && go mod tidy
                cd ..
              fi
            done  

      - name: ✅ Run golangci-lint via Taskfile
        env:
          MODULES: ${{ inputs.modules }}
          GOLANGCI_LINT_VERSION: ${{ inputs.golangci-lint-version }}
        run: task lint
